/*
 * LIDARSCAN_type.cpp
 *
 *  Created on: 01.05.2016
 *      Author: Autogenerated
 */



#include "LIDARSCAN_type.h"

extern "C"
{

RC_t LIDARSCAN_scaleR2D( const LIDARSCAN_raw_t * const praw, LIDARSCAN_data_t * const pvalue)
{

	//Translate SDO data into lidar scann application data
	return RC_ERROR;
}

RC_t LIDARSCAN_scaleD2R( const LIDARSCAN_data_t * const pvalue, LIDARSCAN_raw_t * const praw)
{

	return RC_ERROR;
}

} //extern  "C"
